[package]
name = 'aptos-app'
version = '1.0.0'
[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
AppAdmin = "b2e957f9ba9818d7a95302658a2f0c7af1f71e0a2c63029e504a2d3e294ee186"

##Replace address with your own
